language: java
install: mvn clean verify -B -V -Pintegration-tests
script:
  - cd cloudsim-plus && mvn jacoco:report
  #Upload the coverage report to codacy.com. It requires the CODACY_PROJECT_TOKEN environment variable
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk8
  - openjdk15
